---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-admin-credentials
  namespace: gitops-secrets-demo
spec:
  encryptedData:
    password: AgBXviVGodEAjX2Ax8GWpC8WScSU9mgsFUACF06dHVJfhf3s+4XthueYHBGWpvZ4YlqJ6Ygx6MT70khGR7xL71GZm/dYJ2ekmooqCURQlNONudOCU3czmWMcDYx8yV1teAkvgKlDdd87svKkmLvpMzSy/3EIKOOu/T5WnhUcPkMbf9QiaT5b1nj8leB7lpNHcUQyNU+vnZMj/o+O7wyxqUudZwMsbFpR9LsEgtJJW6r9yHUnWvTVu27QvLSU2aWpZ0RILwC2DNFARE64SYrSUI54ypJfIctvDcXhdSQCTI6mPITShO2gaw4fUnCs7io80RocNiaT1NNoyBmoCBl0vutplY+5H+MXpRND7ZbaUDijiGn91GqpMkXtWRFooUcsCI4OSkrbmZPwbvRD1+2Vs0HhRtPi3pnpm37hcDraR7AUmKPEOfOjUKG9g94uFCuJV3vODuzz7WHJDE+O/nbqxeeaE1tGXRratsFPumRonZmZCmlHxubi2mOdEbGMifPh3A0H5PE2+w3MlXrgWI16f4CalyUDwAs2g9BkrayNJtfoFoCMU5LmljTXE5vJwAZP5c3kqDLgfPKQ6BxmXTEeOs3KznLYSo0wc7KLhJGxXfXhJ3grtYMG9zJwhxIFERndYN+dhCz2mxGNs0MjNjTkD9ktFB3XUBy89CCc+Yo08rbCb1HkzBjerqlmEbXyXGrzwkzaHKVyJRvSTFZlNljfbZBdfkZnC7Yu+mc=
    username: AgB9QFLdAV0LHxIWB8hlCTwt3w1KMUZ8vlLi41od271XdUneukdyDnYsW9986wF4aRTkENCrmBIssahdqeZsb8KdhYVdKMxkEYLvbf3SjPfx88vLmN/GSzK5sMB2WiFXn91PAuZowqlg/HPRXpqE9JHh5mr6QTapxFSi+ourEnMrWupD0pwmj12EymR+0G9CpE9Anqd6Tyw4AAOL0/jfzp/p0+r+oyU4FVhdE8hBHi2HBk7ljPMScrieiTLradCOKsqmUGGvW/ejk5LajjNcilAHVPPpckZqabE8+breHl5R+/JfW85TtkyT4HFaGRBwvmhZKzyC3enq4K3v5jJ+LZ7B9qIIH6GziV2NRaWm2q7C+PlN7Ki4J9pDFcXVxzIJnzwbAyRxGqiUNoW5NIgWIsWdvrBV/+TCQRIzFzQQ+48SqZyCv5nW1hYcj4DR/3nBivS8bmD5Cc6ntve29jOxmlI+I1kPCcrXGW4XaLHVn4tsZFtP1pQWeB422U2I04rvtOHtejBLejnpMMqPKyaZHPe4D1Kr/GgJRIFrPtZ5ZcpjGiTZWoarHtkddPVcTGvv++YAfBda7N8VVZFJcXprKyIr7imtN/Bgkv7sX0iP4Vxj179pvPIcUDEU23ZeKJleQAS0Wf8yQ93uZeV/6RbhQCtq5SO0bUuUJryyJb7/pRw/FQKiUYM3bYOjPbqz/m5+A2rJ+Cc7mj0YhfQ/AA==
  template:
    metadata:
      name: gitea-admin-credentials
      namespace: gitops-secrets-demo
