---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-admin-credentials
  namespace: gitops-secrets-demo
spec:
  encryptedData:
    password: AgCMt2qUNKBjyHTnI+15HKHFi1t9Yaq9d29NF9LgCrPiLjKs/p9/cC1/QmShk/mVlNU8wOW7xpSsf9KsgNxLalmHJ/wyTTFxCsvukCXd1akEtY1wGG5mjilqTrQHDo1041mwLV1jE7qwTZteOztTheeeuF3A1sHVYOi/YX93TqWYGGULj0MZ6vwPGqwS2XwkYANXNUI0DntT2WFT/XOGPXQsi/l7QZE82zbVMnRb0MeJyH2RZjqX0MxA47Y6x021KjBe+c4LVvIsmfkFyv48SrDiGb/OHwoR61FPpblhdT0m641bZgsAdcb4E8L6kV8G5sVUG44FptIyKYnoMia/38ChzlWroB2qYEPV3tYaOkNERWTTMJDnvVGYofbSeoMhGucmttWU4fGBb4Hfhn8O6gF8tQCDlXafdmEmsqAzXfAnys3iQ/NrAI+0EaALjQaC+Nkt2oJuwdEyEDwfTfwPKl0AlWnABD6gtEO9Mx3ranSxua8bDvLFYDAd02NQOJ5tH6RovxthxCA9afeBZ5o9OOF4yv6+W81kMgtGZqGitqZkrWMdZMVvdv+hgbe1tzovOLuF3i/pyHKZ102kya/R2HKqo0TGz1EHeJSwiB/F8IQFy14aGgrLJyz02RcBxmQIEPdIWCFinKFf6q85Az1QM3ddUelsixyvdwCMrTUYIPCToyqVrpXNjunpy+VF/0z9gx/xzXmLcsAsiAFrY1U=
    username: AgBKx/SVnlNrs+fHTJtFv6UyY4hrNQ5wJZbuFd1kX/5UdzwywGb+21A1wZpqNDaJDRPbE2TRRJ0xd5w5Ms/j+eL92E8c1XEumWrHVAli1yYDub65C/z4J8S5n+xi2EJVgO626ewS69r2O3iqwZy9QizwDp7TH38kYw4xWN7JXmaDxzJXDEgiu+JObiADoIIC1Mvno3sJ0NGUvSMApFM1m5dEP38vxl4lIkvq497QNYApEY0UdkVF8V/9JCd6o0HaLgUB+EXh38w3+QPkJvOycf3DZiG9mc3asCv6lNvPaVpuVInbVoT2jYkEWnclyUHJMJrov/Qj0rzIj+blNPlbgxXCQsp9yqsx5DSjg9nAgVz4i3lXGbDGfNxPBqFO5d+TPkEoBP+iCDn+ZMtI+Ihx5Qy1NUpQbP3bx+WLrcl1x5q8s8fmHQ6WKu8T0jZ049jWq7Q67kBbV8CgnvyMQN9KqKrqPK3lZibE/AyLNWiHMvV1PI152diEV4SHiY6VnLEnkciSch5Trrd7bUA9+xw/rdFNOykVKmF/oZxK5C4T0dBXy/R0AJuqv6xjaOTVvVLyp8mPB8GWgBUOHu/Ti8MKcjuhaNooJcTxfNFz3r+ZVf3nbtH0clBKpM0g5yKygMntxbBiWgKk0gRcOUrNqBxVhABpS8X+6oxJ+rqRg5aoNHxfRq/NHEDrXYMisCumeoyEudM27tpEkrPgn5pMvw==
  template:
    metadata:
      name: gitea-admin-credentials
      namespace: gitops-secrets-demo
